// This script reads the current i18n.ts, extracts the keys array structure,
// adds missing keys, and regenerates the file.
const fs = require('fs');

// Missing keys with all 13 locale translations (en, zh, ja, fr, de, es, it, pt, pt-BR, ar, fa, hi, ko)
const missingKeys = [
  ["from", "From", "来自", "から", "De", "Von", "De", "Da", "De", "De", "من", "از", "से", "부터"],
  ["madeToOrderDesc", "Each piece is made to order, ensuring personal craftsmanship and attention to detail.", "每件作品均按单制作，确保个人工艺与细节关注。", "各アイテムは受注生産で、職人の技術と細部へのこだわりを保証します。", "Chaque pièce est faite sur commande, garantissant un artisanat personnel et une attention aux détails.", "Jedes Stück wird auf Bestellung gefertigt, was persönliche Handwerkskunst und Liebe zum Detail gewährleistet.", "Cada pieza se hace por encargo, garantizando artesanía personal y atención al detalle.", "Ogni pezzo è fatto su ordinazione, garantendo artigianato personale e attenzione ai dettagli.", "Cada peça é feita sob encomenda, garantindo artesanato pessoal e atenção aos detalhes.", "Cada peça é feita sob encomenda, garantindo artesanato pessoal e atenção aos detalhes.", "كل قطعة مصنوعة حسب الطلب، مما يضمن الحرفية الشخصية والاهتمام بالتفاصيل.", "هر قطعه سفارشی ساخته می‌شود و حرفه‌ای بودن و توجه به جزئیات را تضمین می‌کند.", "प्रत्येक टुकड़ा ऑर्डर पर बनाया जाता है, जो व्यक्तिगत शिल्पकौशल और विस्तार पर ध्यान सुनिश्चित करता है।", "각 작품은 주문 제작되어 개인적인 장인정신과 세부 사항에 대한 관심을 보장합니다."],
  ["whiteGloveDeliveryDesc", "Our team delivers and places each piece in your home, with care and precision.", "我们的团队精心准确地将每件作品送达并安置在您家中。", "私たちのチームが各アイテムを丁寧かつ正確にご自宅にお届けし、設置します。", "Notre équipe livre et place chaque pièce dans votre maison, avec soin et précision.", "Unser Team liefert und platziert jedes Stück in Ihrem Zuhause, mit Sorgfalt und Präzision.", "Nuestro equipo entrega y coloca cada pieza en su hogar, con cuidado y precisión.", "Il nostro team consegna e posiziona ogni pezzo nella tua casa, con cura e precisione.", "Nossa equipe entrega e coloca cada peça em sua casa, com cuidado e precisão.", "Nossa equipe entrega e coloca cada peça em sua casa, com cuidado e precisão.", "فريقنا يوصل ويضع كل قطعة في منزلك بعناية ودقة.", "تیم ما هر قطعه را با دقت و مراقبت به خانه شما تحویل و نصب می‌کند.", "हमारी टीम आपके घर में प्रत्येक टुकड़ा सावधानी और सटीकता के साथ पहुंचाती और रखती है।", "저희 팀은 각 작품을 정확하고 조심스럽게 고객의 집에 배달하고 배치합니다."],
  ["qualityGuaranteeDesc", "If your piece doesn't meet expectations within 14 days, we'll make it right.", "如果14天内作品不符合期望，我们将妥善解决。", "14日以内にアイテムが期待に沿わない場合、適切に対応いたします。", "Si votre pièce ne répond pas à vos attentes sous 14 jours, nous ferons le nécessaire.", "Wenn Ihr Stück innerhalb von 14 Tagen nicht Ihren Erwartungen entspricht, werden wir es richtigstellen.", "Si tu pieza no cumple con las expectativas en 14 días, lo solucionaremos.", "Se il tuo pezzo non soddisfa le aspettative entro 14 giorni, rimedieremo.", "Se sua peça não atender às expectativas em 14 dias, resolveremos.", "Se sua peça não atender às expectativas em 14 dias, resolveremos.", "إذا لم تلبي قطعتك التوقعات خلال 14 يوماً، سنعالج الأمر.", "اگر قطعه شما ظرف ۱۴ روز انتظارات را برآوره نکرد، ما آن را اصلاح می‌کنیم.", "यदि आपका टुकड़ा 14 दिनों के भीतर अपेक्षाओं पर खरा नहीं उतरता है, तो हम इसे सही करेंगे।", "14일 이내에 작품이 기대에 미치지 못하면, 저희가 해결해 드립니다."],
  ["whatIsAnimalSofaDesc1", "An animal sofa is furniture shaped by nature's forms — the curve of a bear's back, the arch of a lion's mane, the stillness of an owl.", "动物沙发是以自然形态为灵感的家具——熊背的曲线、狮子鬃毛的弧度、猫头鹰的静谧。", "アニマルソファとは自然の形から生まれた家具です — 熊の背のカーブ、ライオンのたてがみのアーチ、フクロウの静けさ。", "Un canapé animal est un mobilier façonné par les formes de la nature — la courbe du dos d'un ours, l'arche de la crinière d'un lion, l'immobilité d'un hibou.", "Ein Tier-Sofa ist Möbel, das von den Formen der Natur geprägt ist — die Kurve eines Bärenrückens, der Bogen einer Löwenmähne, die Stille einer Eule.", "Un sofá animal es mobiliario moldeado por las formas de la naturaleza — la curva del lomo de un oso, el arco de la melena de un león, la quietud de un búho.", "Un divano animale è un mobile plasmato dalle forme della natura — la curva della schiena di un orso, l'arco della criniera di un leone, l'immobilità di un gufo.", "Um sofá animal é mobiliário moldado pelas formas da natureza — a curva das costas de um urso, o arco da juba de um leão, a imobilidade de uma coruja.", "Um sofá animal é mobiliário moldado pelas formas da natureza — a curva das costas de um urso, o arco da juba de um leão, a imobilidade de uma coruja.", "أريكة الحيوان هي أثاث تشكله أشكال الطبيعة — انحناء ظهر الدب، قوس لبد الأسد، سكون البومة.", "مبل حیوانی مبلمانی است که با فرم‌های طبیعت شکل گرفته — انحنای پشت خرس، قوس یال شیر، سکوت جغد.", "पशु सोफा वह फर्नीचर है जो प्रकृति के आकारों से ढला है — भालू की पीठ का घुमाव, शेर की अदम का चाप, उल्लू की शांति।", "애니멀 소파는 자연의 형태로 빚어진 가구입니다 — 곰 등의 곡선, 사자 갈기의 아치, 올빼미의 고요함."],
  ["whatIsAnimalSofaDesc2", "It's not themed furniture. It's sculpture you can sit on — where the silhouette of an animal becomes the architecture of comfort.", "它不是主题家具。它是可以坐的雕塑——动物的轮廓成为舒适的建筑。", "これはテーマ家具ではありません。座れる彫刻です — 動物のシルエットが快適さの建築になります。", "Ce n'est pas du mobilier thématique. C'est de la sculpture sur laquelle on peut s'asseoir — où la silhouette d'un animal devient l'architecture du confort.", "Es ist kein thematisches Möbelstück. Es ist Skulptur, auf der man sitzen kann — wo die Silhouette eines Tieres zur Architektur des Komforts wird.", "No es mobiliario temático. Es escultura en la que puedes sentarte — donde la silueta de un animal se convierte en la arquitectura del confort.", "Non è mobilia a tema. È scultura su cui puoi sederti — dove la sagoma di un animale diventa l'architettura del comfort.", "Não é mobiliário temático. É escultura em que você pode sentar — onde a silhueta de um animal se torna a arquitetura do conforto.", "Não é mobiliário temático. É escultura em que você pode sentar — onde a silhueta de um animal se torna a arquitetura do conforto.", "إنها ليست أثاثاً موضوعياً. إنها منحوتات يمكنك الجلوس عليها — حيث يصبح ظل الحيوان بنية الراحة.", "این مبلمان تماتیکی نیست. این مجسمه‌ای است که می‌توانید روی آن بنشینید — جایی که سیلوئت حیوان به معماری آسایش تبدیل می‌شود.", "यह थीम वाला फर्नीचर नहीं है। यह मूर्तिकला है जिस पर आप बैठ सकते हैं — जहाँ जानवर की सिल्हूट आराम की वास्तुकला बन जाती है।", "테마 가구가 아닙니다. 앉을 수 있는 조각입니다 — 동물의 실루엣이 편안함의 건축이 되는 곳."],
  ["whatIsAnimalSofaDesc3", "Each piece begins as a hand-drawn sketch in our Shanghai workshop, then takes shape through sculpting, framing, and upholstery — a process that takes 8–12 weeks.", "每件作品始于上海工坊的手绘草图，经过雕刻、框架和软装——历时8-12周。", "各アイテムは上海のワークショップでの手描きスケッチから始まり、彫刻、フレーム、張り地を経て形になります — 8〜12週間の工程です。", "Chaque pièce commence par un croquis dessiné à la main dans notre atelier de Shanghai, puis prend forme par la sculpture, l'encadrement et le tapissage — un processus de 8 à 12 semaines.", "Jedes Stück beginnt als handgezeichneter Entwurf in unserer Shanghai-Werkstatt und nimmt dann durch Schnitzen, Rahmen und Polstern Gestalt an — ein Prozess von 8–12 Wochen.", "Cada pieza comienza como un boceto dibujado a mano en nuestro taller de Shanghái, luego toma forma a través de la escultura, el enmarcado y la tapicería — un proceso de 8 a 12 semanas.", "Ogni pezzo inizia come uno schizzo disegnato a mano nel nostro laboratorio di Shanghai, poi prende forma attraverso scultura, intelaiatura e tappezzeria — un processo di 8-12 settimane.", "Cada peça começa como um esboço desenhado à mão em nossa oficina de Shanghai, depois toma forma através de escultura, estrutura e estofamento — um processo de 8 a 12 semanas.", "Cada peça começa como um esboço desenhado à mão em nossa oficina de Xangai, depois toma forma através de escultura, estrutura e estofamento — um processo de 8 a 12 semanas.", "تبدأ كل قطعة كرسم يدوي في ورشتنا في شنغهاي، ثم تأخذ شكلها من خلال النحت والتأطير والتنجيد — عملية تستغرق 8-12 أسبوعاً.", "هر قطعه به عنوان طرح دستی در کارگاه شانگهای آغاز می‌شود، سپس از طریق مجسم‌سازی، قاب‌گذاری و روکش‌گذاری شکل می‌گیرد — فرآیندی ۸ تا ۱۲ هفته‌ای.", "प्रत्येक टुकड़ा हमारी शंघाई वर्कशॉप में हाथ से बनाए गए स्केच के रूप में शुरू होता है, फिर शिल्पकारी, फ्रेमिंग और असबाब के माध्यम से आकार लेता है — एक प्रक्रिया जिसमें 8-12 सप्ताह लगते हैं।", "각 작품은 상하이 워크숍에서 수작업 스케치로 시작되어, 조각, 프레이밍, 실내장 과정을 거쳐 형태를 갖춥니다 — 8-12주가 소요되는 과정입니다."],
  ["cartEmpty", "Your cart is empty", "购物车为空", "カートは空です", "Votre panier est vide", "Ihr Warenkorb ist leer", "Tu carrito está vacío", "Il tuo carrello è vuoto", "Seu carrinho está vazio", "Seu carrinho está vazio", "سلتك فارغة", "سبد خرید شما خالی است", "आपका कार्ट खाली है", "장바구니가 비어 있습니다"],
  ["free", "Free", "免费", "無料", "Gratuit", "Kostenlos", "Gratis", "Gratuito", "Grátis", "Grátis", "مجاني", "رایگان", "मुफ्त", "무료"],
  ["whiteGloveGuarantee", "White-Glove Guarantee", "白手套保证", "ホワイトグローブ保証", "Garantie gants blancs", "White-Glove-Garantie", "Garantía guante blanco", "Garanzia guanto bianco", "Garantia luva branca", "Garantia luva branca", "ضمان القفاز الأبيض", "گارانتی دستکش سفید", "व्हाइट-ग्लव गारंटी", "화이트글로브 보장"],
  ["orderReceived", "Order Received", "订单已收到", "注文を受領しました", "Commande reçue", "Bestellung eingegangen", "Pedido recibido", "Ordine ricevuto", "Pedido recebido", "Pedido recebido", "تم استلام الطلب", "سفارش دریافت شد", "ऑर्डर प्राप्त हुआ", "주문 접수 완료"],
  ["orderReceivedDesc", "We've received your order and will be in touch shortly to confirm details and timeline.", "我们已收到您的订单，将尽快与您确认详情和时间安排。", "注文を受領しました。詳細とスケジュールについてまもなくご連絡いたします。", "Nous avons bien reçu votre commande et vous contacterons sous peu pour confirmer les détails et le délai.", "Wir haben Ihre Bestellung erhalten und werden uns in Kürze zur Bestätigung der Details und des Zeitplans melden.", "Hemos recibido tu pedido y nos pondremos en contacto pronto para confirmar los detalles y el plazo.", "Abbiamo ricevuto il tuo ordine e ti contatteremo a breve per confermare i dettagli e le tempistiche.", "Recebemos seu pedido e entraremos em contato em breve para confirmar os detalhes e o prazo.", "Recebemos seu pedido e entraremos em contato em breve para confirmar os detalhes e o prazo.", "لقد تلقينا طلبك وسنتواصل معك قريباً لتأكيد التفاصيل والمواعيد.", "سفارش شما را دریافت کردیم و به زودی برای تأیید جزئیات و زمان‌بندی با شما تماس خواهیم گرفت.", "हमने आपका ऑर्डर प्राप्त कर लिया है और जल्द ही विवरण और समयसीमा की पुष्टि के लिए संपर्क करेंगे।", "주문을 접수했으며, 세부 사항과 일정을 확인하기 위해 곧 연락드리겠습니다."],
  ["browseCollection", "Browse Collection", "浏览系列", "コレクションを見る", "Parcourir la collection", "Kollektion durchsuchen", "Explorar colección", "Sfoglia collezione", "Explorar coleção", "Explorar coleção", "تصفح المجموعة", "مشاهده مجموعه", "संग्रह ब्राउज़ करें", "컬렉션 둘러보기"],
  ["freeWhiteGlove", "Free White-Glove", "免费白手套", "無料ホワイトグローブ", "Gants blancs gratuits", "Kostenlose White-Glove", "Guante blanco gratis", "Guanto bianco gratuito", "Luva branca grátis", "Luva branca grátis", "قفاز أبيض مجاني", "دستکش سفید رایگان", "मुफ्त व्हाइट-ग्लव", "무료 화이트글로브"],
  ["photoVideoDoc", "Photo & Video Documentation", "照片和视频记录", "写真・動画ドキュメンテーション", "Documentation photo et vidéo", "Foto- und Videodokumentation", "Documentación fotográfica y de video", "Documentazione foto e video", "Documentação de foto e vídeo", "Documentação de foto e vídeo", "توثيق صور وفيديو", "مستند‌سازی عکس و ویدیو", "फोटो और वीडियो दस्तावेज़ीकरण", "사진 및 영상 문서화"],
  ["contactSubtitle", "Get in touch with our team", "与我们的团队联系", "チームにお問い合わせください", "Contactez notre équipe", "Kontaktieren Sie unser Team", "Contacta a nuestro equipo", "Contatta il nostro team", "Entre em contato com nossa equipe", "Entre em contato com nossa equipe", "تواصل مع فريقنا", "با تیم ما تماس بگیرید", "हमारी टीम से संपर्क करें", "저희 팀에 연락하세요"],
  ["messageReceived", "Message Sent", "消息已发送", "メッセージ送信済み", "Message envoyé", "Nachricht gesendet", "Mensaje enviado", "Messaggio inviato", "Mensagem enviada", "Mensagem enviada", "تم إرسال الرسالة", "پیام ارسال شد", "संदेश भेजा गया", "메시지 전송됨"],
  ["messageReceivedDesc", "Thank you for reaching out. We'll respond within 24 hours.", "感谢您的来信。我们将在24小时内回复。", "お問い合わせありがとうございます。24時間以内にご返信いたします。", "Merci de nous avoir contactés. Nous répondrons sous 24 heures.", "Danke für Ihre Nachricht. Wir antworten innerhalb von 24 Stunden.", "Gracias por comunicarte. Responderemos en 24 horas.", "Grazie per averci contattato. Risponderemo entro 24 ore.", "Obrigado pelo contato. Responderemos em 24 horas.", "Obrigado pelo contato. Responderemos em 24 horas.", "شكراً لتواصلك. سنرد خلال 24 ساعة.", "سپاس از تماس شما. ظرف ۲۴ ساعت پاسخ خواهیم داد.", "संपर्क करने के लिए धन्यवाद। हम 24 घंटे में जवाब देंगे।", "연락해 주셔서 감사합니다. 24시간 이내에 답변드리겠습니다."],
  ["name", "Name", "姓名", "お名前", "Nom", "Name", "Nombre", "Nome", "Nome", "Nome", "الاسم", "نام", "नाम", "이름"],
  ["subject", "Subject", "主题", "件名", "Sujet", "Betreff", "Asunto", "Oggetto", "Assunto", "Assunto", "الموضوع", "موضوع", "विषय", "제목"],
  ["orderStatus", "Order Status", "订单状态", "注文状況", "Statut de commande", "Bestellstatus", "Estado del pedido", "Stato ordine", "Status do pedido", "Status do pedido", "حالة الطلب", "وضعیت سفارش", "ऑर्डर स्थिति", "주문 상태"],
  ["tradeBulkPricing", "Trade / Bulk Pricing", "商务/批量价格", "取引・大量価格", "Tarif professionnel / gros", "Handels-/Mengenpreise", "Precios comerciales/al por mayor", "Prezzi commerciali/ingrosso", "Preços comerciais/atacado", "Preços comerciais/atacado", "أسعار تجارية / جملة", "قیمت تجاری/عمده", "व्यापार / थोक मूल्य", "거래 / 대량 가격"],
  ["customMaterialRequest", "Custom Material Request", "定制材质请求", "カスタム素材リクエスト", "Demande de matériau personnalisé", "Individuelle Materialanfrage", "Solicitud de material personalizado", "Richiesta materiale personalizzato", "Solicitação de material personalizado", "Solicitação de material personalizado", "طلب مادة مخصصة", "درخواست مواد سفارشی", "कस्टम सामग्री अनुरोध", "맞춤 소재 요청"],
  ["message", "Message", "留言", "メッセージ", "Message", "Nachricht", "Mensaje", "Messaggio", "Mensagem", "Mensagem", "رسالة", "پیام", "संदेश", "메시지"],
  ["getInTouch", "Get in Touch", "联系我们", "お問い合わせ", "Nous contacter", "Kontakt aufnehmen", "Ponte en contacto", "Mettiti in contatto", "Entre em contato", "Entre em contato", "تواصل معنا", "تماس بگیرید", "संपर्क करें", "문의하기"],
  ["generalInquiries", "General Inquiries", "一般咨询", "一般的なお問い合わせ", "Demandes générales", "Allgemeine Anfragen", "Consultas generales", "Richieste generali", "Consultas gerais", "Consultas gerais", "استفسارات عامة", "سوالات عمومی", "सामान्य पूछताछ", "일반 문의"],
  ["bulkHospitalityPricing", "Bulk / Hospitality Pricing", "批量/酒店价格", "大量・ホテル価格", "Tarifs gros / hôtellerie", "Mengen-/Hotelpreise", "Precios al por mayor / hostelería", "Prezzi ingrosso / hotel", "Preços atacado / hotelaria", "Preços atacado / hotelaria", "أسعار الجملة / الضيافة", "قیمت عمده / هتلداری", "थोक / आतिथ्य मूल्य", "대량 / 호스피탈리티 가격"],
  ["other", "Other", "其他", "その他", "Autre", "Sonstiges", "Otro", "Altro", "Outro", "Outro", "أخرى", "سایر", "अन्य", "기타"],
  ["workshop", "Workshop", "工坊", "ワークショップ", "Atelier", "Werkstatt", "Taller", "Laboratorio", "Oficina", "Oficina", "ورشة", "کارگاه", "वर्कशॉप", "워크숍"],
  ["byAppointmentOnly", "By appointment only", "仅限预约", "予約制", "Sur rendez-vous uniquement", "Nur nach Vereinbarung", "Solo con cita previa", "Solo su appuntamento", "Somente com agendamento", "Somente com agendamento", "بالموعد فقط", "فقط با قرار ملاقات", "केवल नियुक्ति पर", "예약에 한함"],
  ["responseTime", "Response Time", "回复时间", "返信時間", "Temps de réponse", "Antwortzeit", "Tiempo de respuesta", "Tempo di risposta", "Tempo de resposta", "Tempo de resposta", "وقت الاستجابة", "زمان پاسخ", "प्रतिक्रिया समय", "응답 시간"],
  ["within24Hours", "Within 24 hours", "24小时内", "24時間以内", "Sous 24 heures", "Innerhalb von 24 Stunden", "En 24 horas", "Entro 24 ore", "Em 24 horas", "Em 24 horas", "خلال 24 ساعة", "ظرف ۲۴ ساعت", "24 घंटे में", "24시간 이내"],
  ["followUs", "Follow Us", "关注我们", "フォローする", "Suivez-nous", "Folgen Sie uns", "Síguenos", "Seguici", "Siga-nos", "Siga-nos", "تابعنا", "ما را دنبال کنید", "हमें फ़ॉलो करें", "팔로우하세요"],
  ["forTradeHospitality", "For Trade & Hospitality", "商务与酒店", "取引・ホテル向け", "Pour le commerce et l'hôtellerie", "Für Handel & Gastronomie", "Para comercio y hostelería", "Per commercio e hotel", "Para comércio e hotelaria", "Para comércio e hotelaria", "للتجارة والضيافة", "برای تجارت و هتلداری", "व्यापार और आतिथ्य के लिए", "거래 및 호스피탈리티용"],
  ["forTradeHospitalityDesc", "We offer trade pricing for interior designers, architects, and hospitality projects. Contact us for bulk orders and custom specifications.", "我们为室内设计师、建筑师和酒店项目提供商务价格。请联系我们了解批量订单和定制规格。", "インテリアデザイナー、建築家、ホテルプロジェクト向けの取引価格をご用意しています。大量注文やカスタム仕様についてお問い合わせください。", "Nous proposons des tarifs professionnels pour les designers d'intérieur, architectes et projets hôtellers. Contactez-nous pour les commandes en gros et spécifications personnalisées.", "Wir bieten Handelspreise für Innenarchitekten, Architekten und Gastgewerbeprojekte. Kontaktieren Sie uns für Mengenbestellungen und individuelle Spezifikationen.", "Ofrecemos precios comerciales para diseñadores de interiores, arquitectos y proyectos de hostelería. Contáctenos para pedidos al por mayor y especificaciones personalizadas.", "Offriamo prezzi commerciali per designer d'interni, architetti e progetti alberghieri. Contattaci per ordini all'ingrosso e specifiche personalizzate.", "Oferecemos preços comerciais para designers de interiores, arquitetos e projetos de hotelaria. Entre em contato para pedidos em grande quantidade e especificações personalizadas.", "Oferecemos preços comerciais para designers de interiores, arquitetos e projetos de hotelaria. Entre em contato para pedidos em grande quantidade e especificações personalizadas.", "نقدم أسعار تجارية لمصممي الديكور الداخلي والمهندسين المعماريين ومشاريع الضيافة. تواصل معنا للطلبات بالجملة والمواصفات المخصصة.", "ما قیمت تجاری برای طراحان داخلی، معماران و پروژه‌های هتلداری ارائه می‌دهیم. برای سفارش‌های عمده و مشخصات سفارشی با ما تماس بگیرید.", "हम इंटीरियर डिज़ाइनर, आर्किटेक्ट और आतिथ्य परियोजनाओं के लिए व्यापार मूल्य प्रदान करते हैं। थोक ऑर्डर और कस्टम विशिष्टताओं के लिए हमसे संपर्क करें।", "인테리어 디자이너, 건축가 및 호스피탈리티 프로젝트를 위한 거래 가격을 제공합니다. 대량 주문 및 맞춤 사양은 문의해 주세요."],
  ["ourMaterials", "Our Materials", "我们的材质", "私たちの素材", "Nos matériaux", "Unsere Materialien", "Nuestros materiales", "I nostri materiali", "Nossos materiais", "Nossos materiais", "موادنا", "مواد ما", "हमारी सामग्री", "우리의 소재"],
  ["cloudTouchDesc", "Ultra-soft long-pile fabric that creates a dreamlike, cloud-like texture. Perfect for creating statement pieces that invite you to sink in.", "超柔软长毛绒面料，营造如梦如云的质感。非常适合打造令人沉陷其中的标志性作品。", "超柔らかいロングパイル生地。夢のような雲の質感を生み出し、沈み込みたくなるアイテムに最適。", "Tissu ultra-doux à poils longs qui crée une texture onirique et nuageuse. Parfait pour créer des pièces d'exception qui invitent à s'y lover.", "Ultra-weiches Langflorgewebe, das eine traumhafte, wolkenähnliche Textur erzeugt. Perfekt für Statement-Stücke, die zum Versinken einladen.", "Tejido ultra-suave de pelo largo que crea una textura onírica y nubosa. Perfecto para crear piezas que invitan a hundirse.", "Tessuto ultra-morbido a pelo lungo che crea una texture onirica e nuvolosa. Perfetto per creare pezzi che invitano ad affondare.", "Tecido ultra-macio de pelo longo que cria uma textura onírica e nublada. Perfeito para criar peças que convidam a afundar.", "Tecido ultra-macio de pelo longo que cria uma textura onírica e nublada. Perfeito para criar peças que convidam a afundar.", "قماش فائق النعومة ذو وبرة طويلة يخلق ملمساً حلماً سحابياً. مثالي لابتكار قطع تأسرني تدعوك للغوص فيها.", "پارچه بسیار نرم با پرز بلند که بافت رویایی و ابری ایجاد می‌کند. عالی برای ساخت قطعات خاص که دعوت به فرو رفتن می‌کنند.", "अल्ट्रा-सॉफ्ट लॉन्ग-पाइल फैब्रिक जो सपने जैसी, बादल जैसी बनावट बनाता है। ऐसे स्टेटमेंट पीस बनाने के लिए एकदम सही जो आपको धंसने का निमंत्रण दें।", "초소프트 롱파일 원단으로 꿈결 같은 구름 질감을 만듭니다. 푹 빠져들고 싶은 시그니처 작품을 만들기에 완벽합니다."],
  ["usedIn", "Used in", "用于", "使用アイテム", "Utilisé dans", "Verwendet in", "Usado en", "Usato in", "Usado em", "Usado em", "مستخدم في", "استفاده شده در", "उपयोग में", "사용 제품"],
  ["wildTouchDesc", "Textured short-pile fabric with a natural, organic feel. Durable yet soft, ideal for high-traffic living spaces.", "质感短毛绒面料，自然有机触感。耐用而柔软，适合高流量生活空间。", "質感のあるショートパイル生地。自然でオーガニックな手触り。耐久性がありながら柔らかく、人が多く行き来するリビングに最適。", "Tissu texturé à poils courts avec une sensation naturelle et organique. Durable mais doux, idéal pour les espaces de vie très fréquentés.", "Strukturiertes Kurzflorgewebe mit natürlichem, organischem Gefühl. Strapazierfähig und doch weich, ideal für stark frequentierte Wohnräume.", "Tejido texturado de pelo corto con sensación natural y orgánica. Duradero pero suave, ideal para espacios muy transitados.", "Tessuto strutturato a pelo corto con sensazione naturale e organica. Duraturo ma morbido, ideale per spazi abitativi molto frequentati.", "Tecido texturizado de pelo curto com sensação natural e orgânica. Durável mas macio, ideal para espaços de convivência muito frequentados.", "Tecido texturizado de pelo curto com sensação natural e orgânica. Durável mas macio, ideal para espaços de convivência muito frequentados.", "قماش مزخرف ذو وبرة قصيرة بإحساس طبيعي وعضوي. متين ولكن ناعم، مثالي للمساحات المعيشية كثيرة الاستخدام.", "پارچه بافت‌دار با پرز کوتاه و حس طبیعی و ارگانیک. بادوام اما نرم، ایده‌آل برای فضاهای زندگی پرتردد.", "बनावटदार शॉर्ट-पाइल फैब्रिक जो प्राकृतिक, कार्बनिक अनुभव देता है। टिकाऊ फिर भी नरम, अधिक उपयोग वाले रहने की जगहों के लिए आदर्श।", "자연스럽고 유기적인 느낌의 짧은 파일 텍스처 원단. 내구성이 있으면서도 부드러워 트래픽이 많은 거실 공간에 이상적입니다."],
  ["leatherTouchDesc", "Premium full-grain leather that develops a beautiful patina over time. Rich, warm, and unmistakably luxurious.", "优质全粒面皮革，随时间推移会产生美丽的包浆。丰富、温暖，奢华感无与伦比。", "プレミアムフルグレインレザー。時が経つほど美しいパティーナが生まれます。リッチで温かみのある贅沢な質感。", "Cuir pleine fleur premium qui développe une belle patine au fil du temps. Riche, chaleureux et indéniablement luxueux.", "Premium Vollnarbenleder, das mit der Zeit eine wunderschöne Patina entwickelt. Reich, warm und unbestreitbar luxuriös.", "Cuero premium de grano completo que desarrolla una hermosa pátina con el tiempo. Rico, cálido e innegablemente lujoso.", "Pelle premium a grano intero che sviluppa una bella patina nel tempo. Ricca, calda e indiscutibilmente lussuosa.", "Couro premium de grão inteiro que desenvolve uma bela pátina com o tempo. Rico, quente e inegavelmente luxuoso.", "Couro premium de grão inteiro que desenvolve uma bela pátina com o tempo. Rico, quente e inegavelmente luxuoso.", "جلد فاخر كامل الحبة يطور باتينا جميلة مع مرور الوقت. غني ودافئ وفاخر بلا شك.", "چرم ممتاز تمام‌دانه که با گذشت زمان پاتینای زیبایی ایجاد می‌کند. غنی، گرم و بی‌شک لوکس.", "प्रीमियम फुल-ग्रेन चमड़ा जो समय के साथ सुंदर पैटिना विकसित करता है। समृद्ध, गर्म और निर्विवाद रूप से भव्य।", "프리미엄 풀그레인 가죽으로 시간이 지날수록 아름다운 파티나가 발생합니다. 풍부하고 따뜻하며 의심할 여지 없이 럭셔리합니다."],
  ["howFuzzSofaIsMade", "How Fuzz Sofa Is Made", "Fuzz Sofa 的制作过程", "Fuzz Sofaの製造工程", "Comment est fabriqué Fuzz Sofa", "Wie Fuzz Sofa hergestellt wird", "Cómo se fabrica Fuzz Sofa", "Come viene fatto Fuzz Sofa", "Como a Fuzz Sofa é feita", "Como a Fuzz Sofa é feita", "كيف تصنع فاز سوفا", "فاز سوفا چگونه ساخته می‌شود", "फ़ज़ सोफ़ा कैसे बनता है", "Fuzz Sofa는 어떻게 만들어지는가"],
  ["frameConstruction", "Frame Construction", "框架结构", "フレーム構造", "Construction du cadre", "Rahmenkonstruktion", "Construcción del marco", "Costruzione telaio", "Construção da estrutura", "Construção da estrutura", "بناء الإطار", "ساختار قاب", "फ्रेम निर्माण", "프레임 구조"],
  ["frameConstructionDesc", "Solid hardwood frame with reinforced joints, built to last for generations.", "实木硬木框架，加固节点，经久耐用。", "強化接合部を備えた無垢ハードウッドフレーム。何世代にもわたって長持ちします。", "Cadre en bois massif avec joints renforcés, conçu pour durer des générations.", "Massiver Hartholzrahmen mit verstärkten Verbindungen, gebaut für Generationen.", "Marco de madera maciza con juntas reforzadas, hecho para durar generaciones.", "Telaio in legno massello con giunti rinforzati, costruito per durare generazioni.", "Estrutura de madeira maciça com juntas reforçadas, feita para durar gerações.", "Estrutura de madeira maciça com juntas reforçadas, feita para durar gerações.", "إطار خشب صلب مع مفاصل معززة، مصنوع ليدوم أجيالاً.", "قاب چوب سخت با مفاصل تقویت‌شده، ساخته شده برای نسل‌ها.", "सॉलिड हार्डवुड फ्रेम जिसमें रीइनफोर्स्ड जॉइंट्स हैं, पीढ़ियों तक चलने के लिए बनाई गई।", "보강된 이음쇠가 있는 단단한 경목 프레임, 세대를 아울러 지속되도록 제작."],
  ["cushionEngineering", "Cushion Engineering", "坐垫工程", "クッションエンジニアリング", "Ingénierie des coussins", "Polsterkonstruktion", "Ingeniería de cojines", "Ingegneria cuscini", "Engenharia de almofadas", "Engenharia de almofadas", "هندسة الوسائد", "مهندسی بالشت", "कुशन इंजीनियरिंग", "쿠션 엔지니어링"],
  ["cushionEngineeringDesc", "Multi-density foam core wrapped in down feathers for the perfect balance of support and softness.", "多密度泡棉核心包裹鹅绒，完美平衡支撑与柔软。", "マルチデンシティフォームコアにダウンフェザーを巻いた、支えと柔らかさの完璧なバランス。", "Noyau en mousse multi-densité enveloppé de duvet pour l'équilibre parfait entre soutien et douceur.", "Multi-Dichte-Schaumstoffkern, umhüllt von Daunenfedern für die perfekte Balance aus Stützkraft und Weichheit.", "Núcleo de espuma multidensidad envuelto en plumón para el equilibrio perfecto de soporte y suavidad.", "Nucleo in schiuma multi-densità avvolto in piumino per il perfetto equilibrio tra supporto e morbidezza.", "Núcleo de espuma multidensidade envolto em plumas para o equilíbrio perfeito de suporte e maciez.", "Núcleo de espuma multidensidade envolto em plumas para o equilíbrio perfeito de suporte e maciez.", "نواة إسفنج متعدد الكثافة ملفوفة بالريش للتوازن المثالي بين الدعم والنعومة.", "هسته فوم چندچگالی پیچیده شده در پر برای تعادل کامل بین حمایت و نرمی.", "मल्टी-डेंसिटी फोम कोर जो डाउन पंखों में लिपटा है, सपोर्ट और नरमी के बीच सटीक संतुलन के लिए।", "멀티밀도 폼 코어에 다운 깃털을 감싸 지지력과 부드러움의 완벽한 균형을 구현합니다."],
  ["upholsteryDesc", "Every seam and curve is shaped by hand in our Shanghai workshop. Our artisans spend 8-12 weeks on each piece.", "每一条缝线和曲线都由上海工坊手工塑造。每位工匠每件作品耗时8-12周。", "すべての縫い目とカーブは上海のワークショップで手作業で成形されます。職人が各アイテムに8〜12週間かけます。", "Chaque couture et courbe est façonnée à la main dans notre atelier de Shanghai. Nos artisans passent 8 à 12 semaines sur chaque pièce.", "Jede Naht und Kurve wird in unserer Shanghai-Werkstatt von Hand geformt. Unsere Kunsthandwerker verbringen 8-12 Wochen pro Stück.", "Cada costura y curva se moldea a mano en nuestro taller de Shanghái. Nuestros artesanos dedican 8-12 semanas a cada pieza.", "Ogni cucitura e curva è modellata a mano nel nostro laboratorio di Shanghai. I nostri artigiani dedicano 8-12 settimane a ogni pezzo.", "Cada costura e curva é moldada à mão em nossa oficina de Shanghai. Nossos artesãos dedicam 8-12 semanas a cada peça.", "Cada costura e curva é moldada à mão em nossa oficina de Xangai. Nossos artesãos dedicam 8-12 semanas a cada peça.", "كل درز ومنحنى يشكل يدوياً في ورشتنا في شنغهاي. حرفيونا يقضون 8-12 أسبوعاً على كل قطعة.", "هر درز و منحنی به دست در کارگاه شانگهای شکل می‌گیرد. هنرمندان ما ۸ تا ۱۲ هفته برای هر قطعه وقت می‌گذارند.", "हमारी शंघाई वर्कशॉप में हर सीवन और कर्व हाथ से आकार लेता है। हमारे शिल्पकार हर टुकड़े पर 8-12 सप्ताह बिताते हैं।", "모든 이음새와 곡선은 상하이 워크숍에서 수작업으로 성형됩니다. 장인들은 각 작품에 8-12주를 할애합니다."],
  ["finishingQC", "Finishing & QC", "收尾与质检", "仕上げ・品質検査", "Finition et CQ", "Endbearbeitung & QS", "Acabado y CC", "Finitura e QC", "Acabamento e CQ", "Acabamento e CQ", "التشطيب ومراقبة الجودة", "پایان‌کار و کنترل کیفیت", "फिनिशिंग और QC", "마감 및 품질관리"],
  ["finillingQCDesc", "Rigorous quality check covering every stitch, seam, and surface. Only pieces passing our 47-point inspection ship.", "严格的质量检查涵盖每针每线和每个表面。只有通过47项检验的作品才能发货。", "すべての縫い目、ステッチ、表面を対象とした厳格な品質検査。47項目の検査に合格したアイテムのみが出荷されます。", "Contrôle qualité rigoureux couvrant chaque point, couture et surface. Seules les pièces passant notre inspection de 47 points sont expédiées.", "Streng Qualitätsprüfung für jeden Stich, jede Naht und Oberfläche. Nur Stücke, die unsere 47-Punkte-Inspektion bestehen, werden versandt.", "Control de calidad riguroso que cubre cada puntada, costura y superficie. Solo las piezas que pasan nuestra inspección de 47 puntos se envían.", "Rigoroso controllo qualità che copre ogni punto, cucitura e superficie. Solo i pezzi che passano la nostra ispezione a 47 punti vengono spediti.", "Rigoroso controle de qualidade cobrindo cada ponto, costura e superfície. Apenas peças que passam em nossa inspeção de 47 pontos são enviadas.", "Rigoroso controle de qualidade cobrindo cada ponto, costura e superfície. Apenas peças que passam em nossa inspeção de 47 pontos são enviadas.", "فحص جودة صارم يغطي كل غرزة ودرز وسطح. فقط القطع التي تجتاز فحصنا ذو الـ 47 نقطة يتم شحنها.", "کنترل کیفیت سخت‌گیرانه شامل هر بخیه، درز و سطح. فقط قطعاتی که بازرسی ۴۷ نقطه‌ای ما را گذرانده‌اند ارسال می‌شوند.", "हर सिलाई, सीम और सतह को कवर करने वाली कड़ी गुणवत्ता जांच। केवल हमारी 47-बिंदु निरीक्षण पास करने वाले टुकड़े ही भेजे जाते हैं।", "모든 스티치, 이음새 및 표면을 포함하는 엄격한 품질 검사. 47포인트 검사를 통과한 작품만 출하됩니다."],
  ["documentationDelivery", "Documentation & Delivery", "记录与配送", "ドキュメンテーション・配達", "Documentation et livraison", "Dokumentation & Lieferung", "Documentación y entrega", "Documentazione e consegna", "Documentação e entrega", "Documentação e entrega", "التوثيق والتوصيل", "مستند‌سازی و تحویل", "दस्तावेज़ीकरण और डिलीवरी", "문서화 및 배송"],
  ["documentationDeliveryDesc", "Each piece comes with a certificate of authenticity, care guide, and white-glove delivery to your door.", "每件作品附带真品证书、保养指南和白手套上门配送。", "各アイテムには真正証明書、お手入れガイド、ホワイトグローブ配達が付属します。", "Chaque pièce est accompagnée d'un certificat d'authenticité, d'un guide d'entretien et d'une livraison gants blancs à votre porte.", "Jedes Stück kommt mit Echtheitszertifikat, Pflegeleitfaden und White-Glove-Lieferung bis an Ihre Haustür.", "Cada pieza incluye certificado de autenticidad, guía de cuidado y entrega con guante blanco en su puerta.", "Ogni pezzo viene con certificato di autenticità, guida alla cura e consegna con guanto bianco alla porta.", "Cada peça vem com certificado de autenticidade, guia de cuidados e entrega com luva branca na sua porta.", "Cada peça vem com certificado de autenticidade, guia de cuidados e entrega com luva branca na sua porta.", "كل قطعة تأتي مع شهادة أصالة ودليل عناية وتوصيل بقفاز أبيض لباب منزلك.", "هر قطعه با گواهی اصالت، راهنمای نگهداری و تحویل با دستکش سفید درب منزل شما ارائه می‌شود.", "प्रत्येक टुकड़ा प्रामाणिकता प्रमाणपत्र, देखभाल गाइड और आपके दरवाजे तक व्हाइट-ग्लव डिलीवरी के साथ आता है।", "각 작품에는 진품 증명서, 관리 가이드 및 화이트글로브 배송이 포함됩니다."],
  ["bestFor", "Best For", "最适合", "適用途", "Idéal pour", "Am besten für", "Mejor para", "Ideale per", "Melhor para", "Melhor para", "الأفضل لـ", "بهترین برای", "के लिए सर्वोत्तम", "추천 용도"],
  ["category", "Category", "类别", "カテゴリー", "Catégorie", "Kategorie", "Categoría", "Categoria", "Categoria", "Categoria", "الفئة", "دسته‌بندی", "श्रेणी", "카테고리"],
  ["durability", "Durability", "耐久性", "耐久性", "Durabilité", "Haltbarkeit", "Durabilidad", "Durabilità", "Durabilidade", "Durabilidade", "المتانة", "دوام", "टिकाऊपन", "내구성"],
  ["high", "High", "高", "高", "Élevé", "Hoch", "Alto", "Alto", "Alto", "Alto", "عالي", "بالا", "उच्च", "높음"],
  ["mediumHigh", "Medium-High", "中高", "やや高", "Moyen-élevé", "Mittel-hoch", "Medio-alto", "Medio-alto", "Médio-alto", "Médio-alto", "متوسط-عالي", "متوسط-بالا", "मध्यम-उच्च", "중간-높음"],
  ["veryHigh", "Very High", "极高", "非常に高い", "Très élevé", "Sehr hoch", "Muy alto", "Molto alto", "Muito alto", "Muito alto", "عالي جداً", "بسیار بالا", "बहुत उच्च", "매우 높음"],
  ["residentialLowTraffic", "Residential — Low Traffic", "住宅 — 低流量", "住宅 — 低トラフィック", "Résidentiel — faible passage", "Wohnbereich — geringe Beanspruchung", "Residencial — bajo tráfico", "Residenziale — basso traffico", "Residencial — baixo tráfego", "Residencial — baixo tráfego", "سكني — استخدام منخفض", "مسکونی — ترافیک کم", "आवासीय — कम उपयोग", "주거용 — 저트래픽"],
  ["residentialStatement", "Residential — Statement Piece", "住宅 — 标志作品", "住宅 — ステートメントピース", "Résidentiel — pièce d'exception", "Wohnbereich — Statement-Stück", "Residencial — pieza destacada", "Residenziale — pezzo forte", "Residencial — peça de destaque", "Residencial — peça de destaque", "سكني — قطعة بارزة", "مسکونی — قطعه خاص", "आवासीय — स्टेटमेंट पीस", "주거용 — 시그니처 작품"],
  ["contractHighTraffic", "Contract — High Traffic", "商用 — 高流量", "契約 — 高トラフィック", "Contractuel — fort passage", "Vertragsbereich — hohe Beanspruchung", "Contract — alto tráfico", "Contract — alto traffico", "Comercial — alto tráfego", "Comercial — alto tráfego", "تجاري — استخدام عالي", "قراردادی — ترافیک بالا", "कॉन्ट्रैक्ट — उच्च उपयोग", "상업용 — 하이트래픽"],
  ["fabricCare", "Fabric Care", "织物保养", "ファブリックケア", "Entretien du tissu", "Stoffpflege", "Cuidado de la tela", "Cura del tessuto", "Cuidado do tecido", "Cuidado do tecido", "العناية بالقماش", "مراقبت پارچه", "फैब्रिक केयर", "원단 관리"],
  ["fabricCareDesc", "Vacuum regularly with a soft brush attachment. Spot clean with mild detergent. Professional cleaning recommended annually.", "定期使用软刷吸尘器清洁。局部用温和清洁剂擦拭。建议每年专业清洁。", "柔らかいブラシ付き掃除機で定期的にお手入れを。中性洗剤で部分洗い。年1回のプロフェッショナルクリーニングをおすすめします。", "Aspirer régulièrement avec une brosse douce. Nettoyage localisé avec détergent doux. Nettoyage professionnel recommandé annuellement.", "Regelmäßig mit weichem Bürstenaufsatz absaugen. Fleckbehandlung mit mildem Waschmittel. Professionelle Reinigung jährlich empfohlen.", "Aspirar regularmente con cepillo suave. Limpiar manchas con detergente suave. Se recomienda limpieza profesional anual.", "Aspirare regolarmente con bocca morbida. Pulizia localizzata con detergente delicato. Pulizia professionale consigliata annualmente.", "Aspirar regularmente com escova macia. Limpar manchas com detergente suave. Recomendada limpeza profissional anualmente.", "Aspirar regularmente com escova macia. Limpar manchas com detergente suave. Recomendada limpeza profissional anualmente.", "تنظيف بالمكنسة الكهربائية بانتظام مع فرشاة ناعمة. تنظيف البقع بمنظف معتدل. يُنصح بالتنظيف المهني سنوياً.", "جاروبرقی منظم با برس نرم. تمیزکردن لکه با شوینده ملایم. نظافت حرفه‌ای سالانه توصیه می‌شود.", "नरम ब्रश अटैचमेंट के साथ नियमित वैक्यूम। हल्के डिटर्जेंट से स्पॉट क्लीन। वार्षिक प्रोफेशनल क्लीनिंग की सिफारिश।", "부드러운 브러시 부착물로 정기적으로 진공 청소. 순한 세제로 얼룩 제거. 연 1회 전문 세척 권장."],
  ["leatherCare", "Leather Care", "皮革保养", "レザーケア", "Entretien du cuir", "Lederpflege", "Cuidado del cuero", "Cura della pelle", "Cuidado do couro", "Cuidado do couro", "العناية بالجلد", "مراقبت چرم", "लेदर केयर", "가죽 관리"],
  ["leatherCareDesc", "Wipe with a soft, damp cloth. Apply leather conditioner every 3-6 months. Keep away from direct heat and sunlight.", "用柔软湿布擦拭。每3-6个月涂一次皮革护理剂。远离直射热源和阳光。", "柔らかい湿った布で拭く。3〜6ヶ月ごとにレザーコンディショナーを塗布。直射日光と熱源を避けてください。", "Essuyer avec un chiffon doux et humide. Appliquer un conditionneur de cuir tous les 3-6 mois. Éloigner de la chaleur directe et du soleil.", "Mit einem weichen, feuchten Tuch abwischen. Alle 3-6 Monate Lederpflege auftragen. Von direkter Hitze und Sonneneinstrahlung fernhalten.", "Limpiar con un paño suave y húmedo. Aplicar acondicionador de cuero cada 3-6 meses. Mantener alejado del calor y la luz solar directa.", "Pulire con un panno morbido e umido. Applicare balsamo per pelle ogni 3-6 mesi. Tenere lontano da calore e luce solare diretti.", "Limpar com pano macio e úmido. Aplicar condicionador de couro a cada 3-6 meses. Manter longe de calor e luz solar diretos.", "Limpar com pano macio e úmido. Aplicar condicionador de couro a cada 3-6 meses. Manter longe de calor e luz solar diretos.", "مسح بقطعة قماش ناعمة ورطبة. وضع مرطب الجلد كل 3-6 أشهر. إبعاد عن الحرارة وأشعة الشمس المباشرة.", "با پارچه نرم و مرطوب پاک کنید. هر ۳ تا ۶ ماه نرم‌کننده چرم بزنید. از گرما و نور مستقیم خورشید دور نگه دارید.", "नरम, नम कपड़े से पोंछें। हर 3-6 महीने में लेदर कंडीशनर लगाएं। सीधी गर्मी और धूप से दूर रखें।", "부드럽고 축축한 천으로 닦기. 3-6개월마다 가죽 컨디셔너 적용. 직사광선과 열원을 피하세요."],
  ["frameMaintenance", "Frame Maintenance", "框架维护", "フレームメンテナンス", "Entretien du cadre", "Rahmenpflege", "Mantenimiento del marco", "Manutenzione telaio", "Manutenção da estrutura", "Manutenção da estrutura", "صيانة الإطار", "نگهداری قاب", "फ्रेम रखरखाव", "프레임 유지보수"],
  ["frameMaintenanceDesc", "Inspect joints annually. Tighten any loose hardware. Keep away from excessive moisture.", "每年检查节点。拧紧松动的五金件。远离过度潮湿。", "年に1回接合部を点検。緩んだ金具を締める。過度な湿気を避けてください。", "Inspecter les joints annuellement. Serrer la quincaillerie desserrée. Éloigner de l'humidité excessive.", "Jährlich Verbindungen prüfen. Lose Beschläge anziehen. Vor übermäßiger Feuchtigkeit schützen.", "Inspeccionar juntas anualmente. Apretar herrajes flojos. Mantener alejado de la humedad excesiva.", "Ispezionare i giunti annualmente. Stringere eventuali ferramenta allentata. Tenere lontano dall'umidità eccessiva.", "Inspecionar juntas anualmente. Apertar ferragens soltas. Manter longe de umidade excessiva.", "Inspecionar juntas anualmente. Apertar ferragens soltas. Manter longe de umidade excessiva.", "فحص المفاصل سنوياً. شد أي أجهزة فضفاضة. إبعاد عن الرطوبة الزائدة.", "سالانه بازرسی مفاصل. محکم کردن یراق‌آلات شل. دور نگه داشتن از رطوبت زیاد.", "वार्षिक रूप से जोड़ों का निरीक्षण करें। ढीले हार्डवेयर को कसें। अत्यधिक नमी से दूर रखें।", "매년 이음새 점검. 느슨한 하드웨어 조이기. 과도한 습기 피하기."],
  ["cloudMaintenance", "Cloud Maintenance", "云触保养", "クラウドメンテナンス", "Entretien Cloud", "Cloud-Pflege", "Mantenimiento Cloud", "Manutenzione Cloud", "Manutenção Nuvem", "Manutenção Nuvem", "صيانة السحاب", "نگهداری ابری", "क्लाउड रखरखाव", "클라우드 관리"],
  ["wildMaintenance", "Wild Maintenance", "野触保养", "ワイルドメンテナンス", "Entretien Wild", "Wild-Pflege", "Mantenimiento Wild", "Manutenzione Wild", "Manutenção Selvagem", "Manutenção Selvagem", "صيانة البرية", "نگهداری وحشی", "와일드 관리", "와일드 관리"],
  ["leatherMaintenance", "Leather Maintenance", "皮触保养", "レザーメンテナンス", "Entretien Cuir", "Leder-Pflege", "Mantenimiento Cuero", "Manutenzione Pelle", "Manutenção Couro", "Manutenção Couro", "صيانة الجلد", "نگهداری چرمی", "레더 관리", "레더 관리"],
  ["maintenance", "Maintenance", "保养", "メンテナンス", "Entretien", "Wartung", "Mantenimiento", "Manutenzione", "Manutenção", "Manutenção", "الصيانة", "نگهداری", "रखरखाव", "유지보수"],
  ["frameStructure", "Frame Structure", "框架结构", "フレーム構造", "Structure du cadre", "Rahmenstruktur", "Estructura del marco", "Struttura del telaio", "Estrutura da armação", "Estrutura da armação", "هيكل الإطار", "ساختار قاب", "फ्रेम संरचना", "프레임 구조"],
];

// Now read the current i18n.ts, parse the keys, append missing ones, regenerate
const currentContent = fs.readFileSync('/workspace/projects/src/lib/i18n.ts', 'utf8');

// Extract current key names from TranslationKeys type
const keyTypeMatch = currentContent.match(/export type TranslationKeys =\n([\s\S]*?);/);
if (!keyTypeMatch) {
  console.error('Could not find TranslationKeys type');
  process.exit(1);
}
const currentKeys = keyTypeMatch[1].match(/"([^"]+)"/g)?.map(k => k.replace(/"/g, '')) || [];
console.log('Current keys:', currentKeys.length);

// Find keys that are in missingKeys but not in currentKeys
const missingKeyNames = missingKeys.map(k => k[0]);
const trulyMissing = missingKeyNames.filter(k => !currentKeys.includes(k));
console.log('Truly missing keys:', trulyMissing.length);

// We need to add these keys to the translations object as well
// Strategy: insert new key-value pairs into each locale block
// For each missing key, we'll add it after the last key in each locale

const localeIds = ["en", "zh", "ja", "fr", "de", "es", "it", "pt", "pt-BR", "ar", "fa", "hi", "ko"];

let newContent = currentContent;

// Add missing keys to TranslationKeys type
if (trulyMissing.length > 0) {
  const newTypeKeys = trulyMissing.map(k => `  | "${k}"`).join('\n');
  newContent = newContent.replace(
    /export type TranslationKeys =\n/,
    `export type TranslationKeys =\n${newTypeKeys}\n`
  );
  
  // For each locale, find the last key line and insert new keys before the closing },
  // Actually, we need to find each locale block and add the missing keys
  // Let's do it by inserting after "pt-BR": {\n...last_key: ...,\n
  
  for (const localeId of localeIds) {
    const localeKey = localeId.includes('-') ? `"${localeId}"` : localeId;
    // Find the locale block
    const localePattern = new RegExp(`  ${localeKey}: \\{`);
    const localeMatch = newContent.match(localePattern);
    if (!localeMatch) {
      console.error('Could not find locale block for:', localeId);
      continue;
    }
    
    // Find the closing }, for this locale
    const localeStart = newContent.indexOf(localeMatch[0]);
    let depth = 0;
    let localeEnd = -1;
    for (let i = localeStart; i < newContent.length; i++) {
      if (newContent[i] === '{') depth++;
      if (newContent[i] === '}') {
        depth--;
        if (depth === 0) {
          localeEnd = i;
          break;
        }
      }
    }
    
    if (localeEnd === -1) {
      console.error('Could not find end of locale:', localeId);
      continue;
    }
    
    // Insert missing keys before the closing }
    const insertPos = localeEnd;
    let insertStr = '';
    
    for (const mk of missingKeys) {
      if (!trulyMissing.includes(mk[0])) continue;
      const localeIdx = localeIds.indexOf(localeId);
      const value = mk[localeIdx + 1]; // +1 because first element is key name
      const escaped = value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
      insertStr += `    ${mk[0]}: "${escaped}",\n`;
    }
    
    newContent = newContent.substring(0, insertPos) + insertStr + newContent.substring(insertPos);
  }
}

fs.writeFileSync('/workspace/projects/src/lib/i18n.ts', newContent);
console.log('Done! Added', trulyMissing.length, 'keys');
